### ISSUE TITLE
Development tasks

### ISSUE THREAD

**Issue by joachimdalen** [joachimdalen/azdevops-acceptance-criterias#1]
## Major Todos before launch

- [ ] Finish documentation
- [ ] Complete test suite
     - [ ] Refactor to minor components

## Bugs
- [ ] When a work item is deleted, the data is still persisted
- [x] If a document exists, but the work item does not, it is still showed in the criteria list
- [x] Filtering changes the progress to invalid state
- [x] Creating the first criteria from a work item does not add it to the view
- [x] Deleting the last criteria does not show the zero data state
- [x] Updating the required approval alone does not allow you to save the criteria
- [x] Double loader on criteria control
- [x] Identities does not load avatars correctly
- [x] Fetching work items are not batched
- [x] Copy link to criteria will not show if the work item for the criteria is completed, and the option to show completed work items is disabled
- [x] Scroll in criteria modal is weird
- [ ] Invalid flow rejected -> reset to new -> submit for approval -> reject
- [x] Copy link no longer working
- [x] Orphaned no longer working

## Todo

- [ ] Move settings to storage
- [ ] Figure out how to redirect to documentation on install
- [ ] Add onboarding dialog that redirects to documentation?
- [ ] Add confirmation dialog for destructive actions
    - [x] Reset processed criteria
    - [x] Delete criteria
- [ ] Disable changes to processed criteria
- [x] Add error boundaries
- [ ] Add better error handling
    - [ ] Document changed (etag out of match)
    - [ ] Loading failures
- [x] Test in public readonly project?  
- [ ] Improve testing
- [x] Hub does not resize when added as a custom control
- [x] Do we need the ability to add multiple approvers, and should all of them be required?
    - [ ] Should there be an option to configure a "policy" for this?
- [x] Encode criteria link url
- [x] Work item status column
- [ ] Close warning when uncompleted

## Errors to handle
`"typeKey":"InvalidDocumentVersionException","errorCode":0,"eventId":3000`
